version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
    # Group all minor and patch updates together
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "npm"
    # Limit the number of open pull requests
    open-pull-requests-limit: 10
    # Add reviewers
    reviewers:
      - "theinterneti"
    # Configure commit message
    commit-message:
      prefix: "chore"
      include: "scope"
    # Configure versioning strategy
    versioning-strategy: auto

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflow files in the `.github/workflows` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "github-actions"
    # Add reviewers
    reviewers:
      - "theinterneti"
    # Configure commit message
    commit-message:
      prefix: "ci"
      include: "scope"
