services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the project directory
      - ..:/workspace:cached

      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock:rw

      # Mount Git config
      - ~/.gitconfig:/home/node/.gitconfig:ro

      # Use bind mounts for persistent directories in WSL
      - ../node_modules:/workspace/node_modules:cached
      - ~/.npm:/home/node/.npm:cached
      - ~/.vscode-server:/home/node/.vscode-server:cached

    # Forward ports
    ports:
      - "3000:3000"  # Web server (changed from 3000:3000 to avoid port conflict)
      - "9230:9229"  # Node.js debugging (changed from 9229:9229 to avoid potential conflicts)

    # Use host network to ensure VS Code extensions can communicate properly
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Set environment variables
    environment:
      - NODE_ENV=development

    # Keep the container running
    command: sleep infinity

    # Restart policy
    restart: unless-stopped


# No need for named volumes as we're using bind mounts
