version: '3.8'

# This file is used to override the docker-compose.yml file for development
# It will be automatically picked up by docker-compose

services:
  dev:
    # Development-specific settings
    environment:
      - DEBUG=true
      - NODE_ENV=development
      - VSCODE_EXTENSION_DEV=true
    
    # Additional volumes for development
    volumes:
      # VS Code extensions for development
      - ~/.vscode/extensions:/home/node/.vscode-server/extensions:cached
      
      # Additional cache directories
      - vscode-extensions:/home/node/.vscode-server/extensions:cached
      - vscode-insiders:/home/node/.vscode-server-insiders:cached

volumes:
  # Additional volumes for development
  vscode-extensions:
  vscode-insiders:
