name: Performance Monitoring

on:
  # Run on main branch pushes
  push:
    branches: [ main ]
  
  # Run on schedule (once a day)
  schedule:
    - cron: '0 0 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for benchmark history

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run compile

    - name: Download benchmark history
      uses: actions/download-artifact@v4
      with:
        name: benchmark-history
        path: .
      continue-on-error: true  # Continue if no history exists yet

    - name: Run performance monitoring
      run: npm run benchmark:compare

    - name: Upload benchmark history
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-history
        path: benchmark-history.json
        retention-days: 90

    - name: Upload benchmark report
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-report
        path: benchmark-report.md

    - name: Check for performance regressions
      run: |
        if grep -q "PERFORMANCE REGRESSION" benchmark-report.md; then
          echo "::warning::Performance regression detected! Check the benchmark report for details."
        fi
