name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types:
          - feat
          - fix
          - docs
          - style
          - refactor
          - perf
          - test
          - build
          - ci
          - chore
          - revert
        requireScope: false

    - name: Validate branch name
      run: |
        BRANCH_NAME=${GITHUB_HEAD_REF}
        if ! [[ $BRANCH_NAME =~ ^(feature|bugfix|hotfix|release|docs|refactor|test|ci)/[a-z0-9-]+$ ]]; then
          echo "Branch name '$BRANCH_NAME' does not follow the convention: (feature|bugfix|hotfix|release|docs|refactor|test|ci)/name-with-hyphens"
          exit 1
        fi

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Check for TypeScript errors
      run: npm run typecheck